# Generated by Django 5.2.5 on 2025-08-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='summary',
            field=models.TextField(blank=True, help_text='A brief overview of the article', null=True),
        ),
    ]
