# Generated by Django 5.2.5 on 2025-08-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newsarticle_summary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsarticle',
            options={'ordering': ['-published_at'], 'verbose_name': 'News Article', 'verbose_name_plural': 'News Articles'},
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='summary',
            field=models.TextField(default='', help_text='A brief overview of the article'),
        ),
    ]
